# Yates Coley
# rycoley@gmail.com
# 2019 January 08
# This script summarizes accuracy of true state predictions for patients with true state known (from complete CV model re-estimation). AUC, MSE, and MAE are written to csv files.
# This script also generates a pdf with ROC curves and calibration plots



#### WORKFLOW
### 1. Clear workspace
### 2. Define directories, file names
### 3. Load libraries, helper functions
### 4. Load needed data and predictions
### 5. Calculate AUC, MSE, MAE
### 6. Plot ROC curves and calibration


### 1. Clear workspace
rm(list=ls())

### 2. Define directories
#User will need to edit
#This uses CV data and directory locations
base.location <- "/Users/zitongwang/Downloads/prostate-active-surveillance-vDaan/"
location.of.data <- paste0(base.location, "data", sep="") 
location.of.r.scripts <- paste0(base.location, "R-scripts", sep="")
location.of.generated.files <- paste0(base.location, "generated-files-cv/seq-mri-abserror-nolayer", sep="")

# #options to put the plots generated by this script in a different directory
# location.of.assessment.summaries <- location.of.generated.files #paste0(base.location, "generated-files")# "/Users/ryc/Documents/inhealth/prediction-model/automated/for-TIC-assessment-summaries/generated-files"
# 

### 3. Load libraries, helper functions
library("pROC")
library("ROCR")
library("splines")

#define inverse logit function
expit<-function(x){return(exp(x)/(1+exp(x)))}



### 4. Load needed data and predictions
#load(paste(location.of.generated.files,"IOP-data-shaping-work-space.RData", sep="/"))
load("~/Downloads/prostate-active-surveillance-vDaan/generated-files-cv/IOP-data-shaping-work-space.RData")
#number of patients
(n <- dim(pt.data)[1])

#get observed PGGs
eta.data<-pt.data$true.pgg
obs.eta<-eta.data[!is.na(eta.data)]
#put in matrix for PGG>1, PGG>2, PGG>3
obs.eta.mat<-cbind(as.numeric(obs.eta>1), as.numeric(obs.eta>2), as.numeric(obs.eta>3))

K<-4 #number of classes
B<-750  #number of posterior samples

(N<-length(obs.eta))

#list of known true states
eta.true <- pt.data$true.pgg[!is.na(pt.data$true.pgg)]
#number with known true state
n_eta_known <- length(eta.true)

# # get CV groups for 10 folds
# set.seed(44)
# my.sample <- sample(1:n_eta_known)
# folds <- cut(seq(1, n_eta_known), breaks=10, labels=F)
# pt.data$cvgroup<-rep(0,n)
# for(group in 1:10){
#   pt.data$cvgroup[my.sample[folds==group]] <- group}

#get eta predictions
ptdata_cvgroup <- pt.data$cvgroup[1:N] ## 04/15/22 Zitong
fitted.eta<-matrix(nrow=B, ncol=N)
for(group in 1:10){
  obs_eta_cv <- read.csv(paste0(base.location, "generated-files-cv/eta-subj-",group,".csv"))
  fit_eta_cv <- read.csv(paste0(location.of.generated.files, "/eta-fitted-",group,".csv"))
  fit_eta_cv <- fit_eta_cv[,-1]
  group_inx <- which(pt.data$subj %in% obs_eta_cv$subj)
  for(icol in 1:length(group_inx)){
    fitted.eta[,group_inx[icol]] <- fit_eta_cv[,icol]
  }
} ## 04/15/22 Zitong
sum(is.na(fitted.eta)) == 0 # needs to be TRUE
#put into matrix for PGG>1, >2, >3
fitted.inf.obs <- matrix(nrow=N, ncol=(K-1))
for(i in 1:N){for(k in 1:(K-1)){
  fitted.inf.obs[i,k] <- sum(fitted.eta[,i]>k)/B } }



## 5. Calculate AUC
auc.inf.obs<-vector(length=3)
ci.inf.obs<-matrix(nrow=3, ncol=2)
for(j in 1:3){
  auc.inf.obs[j] <-performance( prediction( fitted.inf.obs[,j], obs.eta.mat[,j]), "auc")@y.values[[1]] 
  ci.fit <- ci.auc(response=obs.eta.mat[,j], predictor=fitted.inf.obs[,j], method="bootstrap")
  ci.inf.obs[j,] <- c(ci.fit[1], ci.fit[3])}
auc.inf.obs
#save
#write.csv(as.matrix(cbind(auc.inf.obs, ci.inf.obs)), paste0(location.of.assessment.summaries,"/cv-auc-eta-known.csv"))



## obs_eta versus fitted_eta
obs_fitted_table <- list()
for(irow in 1:nrow(fitted.eta)){
  fitted.eta.i <- fitted.eta[irow,]
  tmp_tbl <- table(obs.eta, fitted.eta.i)
  obs_fitted_table[[irow]] <- matrix(tmp_tbl, ncol = ncol(tmp_tbl), dimnames = dimnames(tmp_tbl))
}
  
ave_obs_fitted <- Reduce("+", obs_fitted_table)/length(obs_fitted_table)
round(ave_obs_fitted)
## fitted_eta versus biopsy data
data.check <- function(condition, message){
  if(condition==FALSE){print(paste(message, "Program terminated.", sep=" "))}
  stopifnot(condition)}
load("generated-files-seq/IOP-data-shaping-work-space.RData")
source("R-script/data-prep-for-jags-reform-addmri.R")
pt.data.short <- pt.data %>% 
  dplyr::select(clinical_PTnum, true.pgg, bx.pgg) %>% 
  filter(!is.na(true.pgg))

bgg_fittedeta_table <- list()
for(irow in 1:nrow(fitted.eta)){
  fitted.eta.i <- fitted.eta[irow,]
  pt.data.short$fitted.pgg <- fitted.eta.i
  tmp.pt.data <- pt.data
  tmp.pt.data <- pt.data %>% left_join(pt.data.short,by = c("clinical_PTnum", "true.pgg", "bx.pgg"))
  pgg.data$fitted.pgg <- tmp.pt.data$fitted.pgg[pgg.data$subj]
  pgg.data2$fitted.pgg <- tmp.pt.data$fitted.pgg[pgg.data2$subj]
  fitted_pgg <- c(pgg.data$fitted.pgg, pgg.data2$fitted.pgg)
  
  tmp_tbl <- table(fitted_pgg, pgg_data)
  bgg_fittedeta_table[[irow]] <- matrix(tmp_tbl, ncol = ncol(tmp_tbl), dimnames = dimnames(tmp_tbl))
}



ave_bgg_fittedeta <- Reduce("+", bgg_fittedeta_table)/length(bgg_fittedeta_table)
round(ave_bgg_fittedeta)

pgg.data$true.pgg <- eta.data[pgg.data$subj]
pgg.data2$true.pgg <- eta.data[pgg.data2$subj]
table(c(pgg.data$true.pgg, pgg.data2$true.pgg), pgg_data)

