# Yates Coley
# rycoley@gmail.com
# 2019 January 08
# This script summarizes accuracy of true state predictions for patients with true state known (from complete CV model re-estimation). AUC, MSE, and MAE are written to csv files.
# This script also generates a pdf with ROC curves and calibration plots



#### WORKFLOW
### 1. Clear workspace
### 2. Define directories, file names
### 3. Load libraries, helper functions
### 4. Load needed data and predictions
### 5. Calculate AUC, MSE, MAE
### 6. Plot ROC curves and calibration


### 1. Clear workspace
rm(list=ls())

### 2. Define directories
#User will need to edit
#This uses CV data and directory locations
base.location <- "/Users/zitongwang/Downloads/prostate-active-surveillance-vDaan/"
location.of.data <- paste0(base.location, "data", sep="") 
location.of.r.scripts <- paste0(base.location, "R-scripts", sep="")
location.of.generated.files <- paste0(base.location, "generated-files-cv/seq-mri-abserror", sep="")

# #options to put the plots generated by this script in a different directory
# location.of.assessment.summaries <- location.of.generated.files #paste0(base.location, "generated-files")# "/Users/ryc/Documents/inhealth/prediction-model/automated/for-TIC-assessment-summaries/generated-files"
# 

### 3. Load libraries, helper functions
library("pROC")
library("ROCR")
library("splines")

#define inverse logit function
expit<-function(x){return(exp(x)/(1+exp(x)))}



### 4. Load needed data and predictions
#load(paste(location.of.generated.files,"IOP-data-shaping-work-space.RData", sep="/"))
load("~/Downloads/prostate-active-surveillance-vDaan/generated-files-cv/IOP-data-shaping-work-space.RData")
#number of patients
(n <- dim(pt.data)[1])

#get observed PGGs
eta.data<-pt.data$true.pgg
obs.eta<-eta.data[!is.na(eta.data)]
#put in matrix for PGG>1, PGG>2, PGG>3
obs.eta.mat<-cbind(as.numeric(obs.eta>1), as.numeric(obs.eta>2), as.numeric(obs.eta>3))

K<-4 #number of classes
B<-750  #number of posterior samples

(N<-length(obs.eta))

#list of known true states
eta.true <- pt.data$true.pgg[!is.na(pt.data$true.pgg)]
#number with known true state
n_eta_known <- length(eta.true)

# # get CV groups for 10 folds
# set.seed(44)
# my.sample <- sample(1:n_eta_known)
# folds <- cut(seq(1, n_eta_known), breaks=10, labels=F)
# pt.data$cvgroup<-rep(0,n)
# for(group in 1:10){
#   pt.data$cvgroup[my.sample[folds==group]] <- group}

#get eta predictions
ptdata_cvgroup <- pt.data$cvgroup[1:N] ## 04/15/22 Zitong
fitted.eta<-matrix(nrow=B, ncol=N)
for(group in 1:10){
  obs_eta_cv <- read.csv(paste0(base.location, "generated-files-cv/eta-subj-",group,".csv"))
	fit_eta_cv <- read.csv(paste0(location.of.generated.files, "/eta-fitted-",group,".csv"))
	fit_eta_cv <- fit_eta_cv[,-1]
	group_inx <- which(pt.data$subj %in% obs_eta_cv$subj)
	for(icol in 1:length(group_inx)){
	  fitted.eta[,group_inx[icol]] <- fit_eta_cv[,icol]
	}
} ## 04/15/22 Zitong
sum(is.na(fitted.eta)) == 0 # needs to be TRUE
#put into matrix for PGG>1, >2, >3
fitted.inf.obs <- matrix(nrow=N, ncol=(K-1))
for(i in 1:N){for(k in 1:(K-1)){
		fitted.inf.obs[i,k] <- sum(fitted.eta[,i]>k)/B } }



## 5. Calculate AUC
auc.inf.obs<-vector(length=3)
ci.inf.obs<-matrix(nrow=3, ncol=2)
for(j in 1:3){
	auc.inf.obs[j] <-performance( prediction( fitted.inf.obs[,j], obs.eta.mat[,j]), "auc")@y.values[[1]] 
	ci.fit <- ci.auc(response=obs.eta.mat[,j], predictor=fitted.inf.obs[,j], method="bootstrap")
	ci.inf.obs[j,] <- c(ci.fit[1], ci.fit[3])}
auc.inf.obs
#save
#write.csv(as.matrix(cbind(auc.inf.obs, ci.inf.obs)), paste0(location.of.assessment.summaries,"/cv-auc-eta-known.csv"))


# MSE
mse.vec<-vector(length=(K-1))
for(k in 1:(K-1)){
	mse.vec[k]<-mean((fitted.inf.obs[,k]-obs.eta.mat[,k])^2)}
write.csv(mse.vec, paste0(location.of.assessment.summaries,"/cv-mse-eta-known.csv"))

# MAE
mae.vec<-vector(length=(K-1))
for(k in 1:(K-1)){
	mae.vec[k]<-mean(fitted.inf.obs[,k]-obs.eta.mat[,k])}
write.csv(mae.vec, paste0(location.of.assessment.summaries,"/cv-mae-eta-known.csv"))




## 5. Plot ROC and calibration

pdf(paste0(location.of.assessment.summaries,"/cv-predictive-accuracy.pdf"), width=8, height=10)

layout(matrix(c(c(1:6),rep(7,2)), nrow=4, ncol=2, byrow=TRUE), 
       widths=c(4,4), heights=c(rep(3,3),1))

for(j in 1:3){

## Calibration plot
ns.inf.obs<-glm(obs.eta.mat[,j]~ns(fitted.inf.obs[,j],2), family="binomial")
pred.inf.obs<-predict.glm(ns.inf.obs, ns(fitted.inf.obs[,j],2), se.fit=TRUE)

order.inf.obs<-order(fitted.inf.obs[,j])
post.inf.obs<-fitted.inf.obs[,j][order.inf.obs] #these are my posterior predictions
fit.inf.obs<-pred.inf.obs$fit[order.inf.obs] #this is ns model fit
se.inf.obs<-pred.inf.obs$se.fit[order.inf.obs]
fit.up.inf.obs<-pred.inf.obs$fit[order.inf.obs] + qnorm(0.975)*se.inf.obs
fit.low.inf.obs<-pred.inf.obs$fit[order.inf.obs] + qnorm(0.025)*se.inf.obs


plot(obs.eta.mat[,j]~fitted.inf.obs[,j], type="n", xlab="", ylab="", xaxt="n", yaxt="n")#pch=3, xlim=c(0,1))
mtext(c("Probablility PGG > 1", "Probablility PGG > 2", "Probablility PGG >3")[j],1,line=3, cex=1)
mtext("Observed Proportion", 2, line=2.75, cex=1)

Axis(side=1,labels=TRUE, cex.axis=1)
Axis(side=2,labels=TRUE, cex.axis=1)

polygon(x=c(post.inf.obs, rev(post.inf.obs)), c(expit(fit.low.inf.obs), rev(expit(fit.up.inf.obs))) , col="lightblue", border="lightblue")

abline(0,1, lwd=3, lty="dotted")

lines(expit(fit.inf.obs)~post.inf.obs, col="dark blue", lwd=3)

points(jitter(obs.eta.mat[obs.eta==1,j], factor=0.15) ~ fitted.inf.obs[obs.eta==1,j], pch=".", col="green2", cex=3)
points(jitter(obs.eta.mat[obs.eta==2,j], factor=0.15) ~ fitted.inf.obs[obs.eta==2,j], pch=".", col="gold", cex=3)
points(jitter(obs.eta.mat[obs.eta==3,j], factor=0.15) ~ fitted.inf.obs[obs.eta==3,j], pch=".", col="orange", cex=3)
points(jitter(obs.eta.mat[obs.eta==4,j], factor=0.15) ~ fitted.inf.obs[obs.eta==4,j], pch=".", col="red2", cex=3)



## ROC curve
plot(c(0,1),c(0,1), type="n", xlab="", ylab="", xaxt="n", yaxt="n")
mtext("False Positive Rate",1,line=3, cex=1)
mtext("True Positive Rate",2,line=2.75, cex=1)
Axis(side=1,labels=TRUE, cex.axis=1)
Axis(side=2,labels=TRUE, cex.axis=1)

roc.inf.obs<-performance(prediction(fitted.inf.obs[,j], obs.eta.mat[,j]),"tpr","fpr")
lines(roc.inf.obs@y.values[[1]]~roc.inf.obs@x.values[[1]], lwd=3, col=c("gold","orange","red2")[j])

legend("bottomright", legend=paste0("AUC (95% CI) = ",
                                   round(auc.inf.obs[j], 2), "(", 
                                   round(ci.inf.obs[j,1], 2), ", ",
                                   round(ci.inf.obs[j,2], 2), ")"),
       bty="n", pch=NA)

}


par(mar=c(0,0,0,0))
plot(c(0,1), c(0,1), type="n", frame.plot=F, axes=F, xlab="", ylab="")

legend(x=0, y=1.1, title="", legend=c("Natural Spline Regression Fit", "95% pointwise CI"), lwd=c(3,10), col=c("dark blue", "light blue"), bty="n", cex=1.5)

legend(x=0.5, y=0.8, title="Post-Surgery Pathological Grade Group (PGG)", legend=c("1", "2", "3", "4-5"), pch=".", pt.cex=10, col=c("green2", "gold", "orange", "red2"), horiz=TRUE, bty="n", cex=1.5)


dev.off()

